//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilibili.Settings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bilibili.Settings.Setting", typeof(Setting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;app_secret&quot;: &quot;59b43e04ad6965f34319062b478f83dd&quot;,
        ///	&quot;General&quot;: {
        ///		&quot;actionKey&quot;: &quot;appkey&quot;,
        ///		&quot;appkey&quot;: &quot;4409e2ce8ffd12b8&quot;,
        ///		&quot;build&quot;: &quot;5531000&quot;,
        ///		&quot;device&quot;: &quot;android&quot;,
        ///		&quot;mobi_app&quot;: &quot;android&quot;,
        ///		&quot;platform&quot;: &quot;android&quot;
        ///	},
        ///	&quot;PCHeaders&quot;: {
        ///		&quot;Accept&quot;: &quot;application/json, text/plain, */*&quot;,
        ///		&quot;Accept-Encoding&quot;: &quot;deflate&quot;,
        ///		&quot;Accept-Language&quot;: &quot;zh-CN,zh;q:0.9&quot;,
        ///		&quot;User-Agent&quot;: &quot;Mozilla/5.0 BiliDroid/5.53.1 (ccc@gmail.com) os/android model/MI 9 mobi_app/android build/5531000 channel/master innerVer/5 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Bilibili {
            get {
                return ResourceManager.GetString("Bilibili", resourceCulture);
            }
        }
    }
}
